import type { Metadata } from "next"
import { portfolio } from "@/lib/portfolio"

/**
 * Centralized SEO configuration.
 *
 * The site URL is read from `NEXT_PUBLIC_SITE_URL` so it can be configured per
 * environment (preview vs. production). It falls back to a sensible default for
 * local development. Update the fallback to your production domain.
 */
export const siteConfig = {
  url: (process.env.NEXT_PUBLIC_SITE_URL ?? "https://luca-nguyen.dev").replace(/\/$/, ""),
  name: portfolio.identity.fullName,
  title: `${portfolio.identity.fullName} | Fullstack Developer Portfolio`,
  description:
    "Portfolio of Luca Nguyen, a fullstack JavaScript/TypeScript developer specializing in React, Next.js, Node.js and NestJS. Building clean, scalable, production-ready web applications.",
  locale: "en_US",
  ogImage: "/icon.svg",
} as const

/** Keyword set derived from the portfolio's roles and skills. */
const seoKeywords = Array.from(
  new Set([
    portfolio.identity.fullName,
    "Fullstack Developer",
    "Frontend Developer",
    "Backend Developer",
    ...portfolio.identity.roles,
    ...portfolio.skills.categories.flatMap((category) => category.skills.map((skill) => skill.name)),
  ]),
)

/** Base metadata shared across the site, consumed by the root layout. */
export const baseMetadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.title,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: seoKeywords,
  authors: [{ name: siteConfig.name, url: siteConfig.url }],
  creator: siteConfig.name,
  applicationName: `${siteConfig.name} Portfolio`,
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: siteConfig.locale,
    url: siteConfig.url,
    siteName: `${siteConfig.name} Portfolio`,
    title: siteConfig.title,
    description: siteConfig.description,
    // Social preview image is generated by `app/opengraph-image.tsx` and
    // auto-attached by Next.js — no explicit `images` needed here.
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.title,
    description: siteConfig.description,
    // Twitter image is also derived from `app/opengraph-image.tsx`.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/icon-dark-32x32.png", media: "(prefers-color-scheme: dark)" },
      { url: "/icon-light-32x32.png", media: "(prefers-color-scheme: light)" },
    ],
    apple: "/apple-icon.png",
  },
}

/**
 * Builds the JSON-LD structured data describing the portfolio owner and site.
 * Rendered server-side so search engines can parse it without executing JS.
 */
export function buildJsonLd() {
  const sameAs = portfolio.contact.methods
    .map((method) => method.href)
    .filter((href) => href.startsWith("http"))

  const knowsAbout = portfolio.skills.categories.flatMap((category) =>
    category.skills.map((skill) => skill.name),
  )

  const person = {
    "@type": "Person",
    name: portfolio.identity.fullName,
    jobTitle: portfolio.identity.roles[0],
    description: siteConfig.description,
    url: siteConfig.url,
    sameAs,
    knowsAbout,
  }

  return {
    "@context": "https://schema.org",
    "@graph": [
      person,
      {
        "@type": "WebSite",
        name: `${portfolio.identity.fullName} Portfolio`,
        url: siteConfig.url,
        author: { "@type": "Person", name: portfolio.identity.fullName },
      },
    ],
  }
}
